name: zefyrka
description: Clean, minimalistic and collaboration-ready rich text editor for Flutter based on Zefyr package.
version: 1.4.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  url_launcher: ^6.1.2
  quill_format: ^1.0.2
  notus_format: ^1.0.3
  characters: ^1.2.0

dev_dependencies:
  pedantic: ^1.11.0
